version: 0.2

phases:
phases:
  install:
    runtime-versions:
      java: openjdk8
  post_build:
    commands:
      - cd demo
      - mvn clean package
artifacts:
  files:
    - '**/*'
  base-directory: 'target'